# -*- #################
# ---------------------------------------------------------------------------
# Metadataexport.py
# Created on: 2015-02-12 12:51:37.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy, os, logging
from arcpy import env

import libxml2, libxslt

# Get input parameters
ArcGIS_ItemDescription_xsl =  arcpy.GetParameterAsText(0)
IndexPage_xsl = arcpy.GetParameterAsText(1)
inputworkspace =  arcpy.GetParameterAsText(2)
outworkspace = arcpy.GetParameterAsText(3)
env.workspace = outworkspace


# Set up logging
LOG_FILENAME = '\Metadataexport.log'
logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s %(levelname)-8s %(message)s',
                    datefmt='%a, %d %b %Y %H:%M:%S',
                    filename= outworkspace + LOG_FILENAME,
                    filemode='w')

# Delete old html and xml files
os.chdir(outworkspace)
try:
    filelist = [ f for f in os.listdir(".") if f.endswith(".html")  or f.endswith(".xml")]
    for f in filelist:
        os.remove(f)
except:
    logging.info("Delete failure")

#Delete old Category/Subcategory Tables
ExtractTable = inputworkspace + "\MetadataExtract"
CategoryTable = inputworkspace + "\category"
SubcategoryTable = inputworkspace + "\subcategory"

# Delete Old Table
try:
    arcpy.Delete_management(CategoryTable)
    arcpy.Delete_management(SubcategoryTable)
except:
    logging.info(arcpy.GetMessages(2))


# Export configuration tables
try:     
    #Category Table 
    arcpy.Frequency_analysis(ExtractTable,CategoryTable,"CATEGORY","#")
    
    #Subcategory Table
    arcpy.Frequency_analysis(ExtractTable,SubcategoryTable,"CATEGORY;SUBCATEGORY","#")
    
    arcpy.ExportXMLWorkspaceDocument_management(CategoryTable,outworkspace + "/categorytable.xml","DATA","BINARY","NO_METADATA") 
    arcpy.ExportXMLWorkspaceDocument_management(SubcategoryTable,outworkspace + "/subcategorytable.xml","DATA","BINARY","NO_METADATA") 
    arcpy.ExportXMLWorkspaceDocument_management(ExtractTable,outworkspace + "/extracttable.xml","DATA","BINARY","NO_METADATA") 
except:
      logging.info(arcpy.GetMessages(2)) 
     
#Create index page
try:
    parseStyle = libxslt.parseStylesheetFile(IndexPage_xsl)
    parsexml =  libxml2.parseFile(outworkspace + '\extracttable.xml')
    result = parseStyle.applyStylesheet(parsexml, None)
    parseStyle.saveResultToFilename(outworkspace + '\Index.html', result, 0)

    parseStyle.freeStyleDocuments()
    parsexml.freeDoc()
    result.freeDoc()
except:
    logging.info("Index page fail!")


# Create metadata pages
fields = ['DATASOURCE', 'FILENAME']

try:
    with arcpy.da.SearchCursor(ExtractTable, fields) as cursor:
        for row in cursor:
            arcpy.XSLTransform_conversion(row[0], ArcGIS_ItemDescription_xsl,  row[1])
except:
    logging.info(arcpy.GetMessages(2))